/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as EvalsRouteImport } from './routes/evals'
import { Route as CliRouteImport } from './routes/cli'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SkillsSkillIdRouteImport } from './routes/skills/$skillId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsRoute = EvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: '/skills/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/evals': typeof EvalsRoute
  '/governance': typeof GovernanceRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/evals': typeof EvalsRoute
  '/governance': typeof GovernanceRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills': typeof SkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/evals': typeof EvalsRoute
  '/governance': typeof GovernanceRoute
  '/history': typeof HistoryRoute
  '/integrations': typeof IntegrationsRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli'
    | '/evals'
    | '/governance'
    | '/history'
    | '/integrations'
    | '/mcp'
    | '/settings'
    | '/skills/$skillId'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cli'
    | '/evals'
    | '/governance'
    | '/history'
    | '/integrations'
    | '/mcp'
    | '/settings'
    | '/skills/$skillId'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/cli'
    | '/evals'
    | '/governance'
    | '/history'
    | '/integrations'
    | '/mcp'
    | '/settings'
    | '/skills/$skillId'
    | '/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliRoute: typeof CliRoute
  EvalsRoute: typeof EvalsRoute
  GovernanceRoute: typeof GovernanceRoute
  HistoryRoute: typeof HistoryRoute
  IntegrationsRoute: typeof IntegrationsRoute
  McpRoute: typeof McpRoute
  SettingsRoute: typeof SettingsRoute
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals': {
      id: '/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof EvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillId': {
      id: '/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliRoute: CliRoute,
  EvalsRoute: EvalsRoute,
  GovernanceRoute: GovernanceRoute,
  HistoryRoute: HistoryRoute,
  IntegrationsRoute: IntegrationsRoute,
  McpRoute: McpRoute,
  SettingsRoute: SettingsRoute,
  SkillsSkillIdRoute: SkillsSkillIdRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
